[profile.ci.fuzz]
runs = 10_000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
pharosTestnet = "${PHAROS_TESTNET_RPC_URL}"
eduTestnet = "${EDU_TESTNET_RPC_URL}"
 
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
